services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://myuser:password@db:5432/mydatabase"
      DB_HOST: "db"
      DB_USERNAME: "myuser"
      DB_PASSWORD: "password"
    ports:
      - "3000:3000"
      - "9394:9394"
    volumes:
      - .:/rails
    entrypoint: ["/rails/script/db_startup.sh"]
    command: ["rails", "server", "-b", "0.0.0.0"]

volumes:
  postgres_data: